% SOCAT gridded file. According to Corentin, keep it as-is, with added
% Copernicus-specific global attributes
% Split by variable???
clc; clear all; close all
workrootdir=...
    '/Users/rpr061/Dropbox/BCDC_Projects/CMEMS_INSTAC/REP_Products/';
indir=[workrootdir,'04_2018/SOCATv6/original/'];
%outdir=[workrootdir,'2018/SOCATv6/workspace/'];
outdir=['/Users/rpr061/Documents/localtestarea/CMEMS/SOCAT_REP_GRIDDED_FIELDS/'];

gridfiles=dir([indir,'*gridded*']);

%
% Load existing netcdfs
for f=1:length(gridfiles)
   % copyfile([indir,'GLODAPv2.2016b.',varstoadd{v},'.nc'], ...
   %     [outdir]); %Create specific names??

   system(['cp ',indir,gridfiles(f).name,' ',outdir,gridfiles(f).name(1:end-3),'_CMEMS.nc'  ]);
   system(['chflags nouchg ',outdir,gridfiles(f).name(1:end-3),'_CMEMS.nc']);

   ncid=netcdf.open([outdir,gridfiles(f).name(1:end-3),'_CMEMS.nc'], ...
    'NC_WRITE');

netcdf.reDef(ncid);
globid=netcdf.getConstant('GLOBAL');


 netcdf.putAtt(ncid, globid, 'data_type', 'Copernicus Marine gridded data');
 netcdf.putAtt(ncid, globid, 'format_version', '1.0');
 netcdf.putAtt(ncid, globid, 'date_update', datestr(today, 'yyyy-mm-ddTHH:MM:SSZ'));
 netcdf.putAtt(ncid, globid, 'institution', 'Pacific Marine Environmental Laboratory (PMEL), National Oceanic and Atmospheric Administration (NOAA)');
 netcdf.putAtt(ncid, globid, 'institution_edmo_code', '1440');
 netcdf.putAtt(ncid, globid, 'data_mode', 'D');
 netcdf.putAtt(ncid, globid, 'references', 'http://marine.copernicus.eu, http://www.socat.info/');
 netcdf.putAtt(ncid, globid, 'comment', ' ');
 netcdf.putAtt(ncid, globid, 'Conventions', 'CMEMS-INS-PUM-013-049-050');
 netcdf.putAtt(ncid, globid, 'naming_authority', 'Copernicus Marine');
 netcdf.putAtt(ncid, globid, 'id', [gridfiles(f).name(1:end-3),'_CMEMS']);
 netcdf.putAtt(ncid, globid, 'cdm_data_type', 'grid');
 netcdf.putAtt(ncid, globid, 'area', 'Global Ocean');
 netcdf.putAtt(ncid, globid, 'geospatial_lat_min', '-90');
 netcdf.putAtt(ncid, globid, 'geospatial_lat_max', '90');
 netcdf.putAtt(ncid, globid, 'geospatial_lon_min', '-180');
 netcdf.putAtt(ncid, globid, 'geospatial_lon_max', '180');
 netcdf.putAtt(ncid, globid, 'geospatial_vertical_min', '0');
 netcdf.putAtt(ncid, globid, 'geospatial_vertical_max', '5');
 netcdf.putAtt(ncid, globid, 'time_coverage_start', '1970-01-01T00:00:00Z');
 netcdf.putAtt(ncid, globid, 'time_coverage_end', '2018-01-07T23:59:00Z');
 netcdf.putAtt(ncid, globid, 'longitude_resolution', '1.0');
 netcdf.putAtt(ncid, globid, 'latitude_resolution', '1.0');
 if contains(gridfiles(f).name,'coast')
  netcdf.putAtt(ncid, globid, 'longitude_resolution', '0.25');
 netcdf.putAtt(ncid, globid, 'latitude_resolution', '0.25');    
 end
 netcdf.putAtt(ncid, globid, 'contact', 'post@bcdc.uib.no');
 netcdf.putAtt(ncid, globid, 'author', 'SOCAT and Copernicus data provider');
 netcdf.putAtt(ncid, globid, 'data_assembly_center', 'BERGEN');
 netcdf.putAtt(ncid, globid, 'distribution_statement', 'These data follow Copernicus standards; they are public and free of charge. User assumes all risk for use of data. User must display citation in any publication or product using data. User must contact PI prior to any commercial use of data.');
 netcdf.putAtt(ncid, globid, 'citation', ['These data were collected and made freely available by the Copernicus project and the programs that contribute to it. ',...
     'Cite as Bakker et al. (2016) and Bakker et al. (2018)']);
 netcdf.putAtt(ncid, globid, 'update_interval', 'yearly');
 netcdf.putAtt(ncid, globid, 'qc_manual', 'QUID_CMEMS-IN_GLO_CARBON_REP_OBSERVATIONS_013_050');
 netcdf.putAtt(ncid, globid, 'history', 'FERRET V7.4 (optimized) 30-May-18');
 netcdf.putAtt(ncid, globid, 'SOCAT_Notes', 'SOCAT gridded v6 3-May-2018');
 netcdf.putAtt(ncid, globid, 'summary', 'Surface Ocean Carbon Atlas (SOCAT) Gridded (binned) SOCAT observations, with a spatial grid of 1x1 degree and yearly in time. The gridded fields are computed from the monthly 1-degree gridded data, which uses only SOCAT datasets with QC flags of A through D and SOCAT data points flagged with WOCE flag values of 2. This yearly data is computed using data from the start to the end of each year as described in the summary attribute of each variable.');
 netcdf.putAtt(ncid, globid, 'caution', 'NO INTERPOLATION WAS PERFORMED. SIGNIFICANT BIASES ARE PRESENT IN THESE GRIDDED RESULTS DUE TO THE ARBITRARY AND SPARSE LOCATIONS OF DATA VALUES IN BOTH SPACE AND TIME.');
 netcdf.putAtt(ncid, globid, 'title', 'Global Ocean - Surface Ocean CO2 Atlas (SOCAT)');

netcdf.putAtt(ncid, globid, 'Citation_SOCAT_Publication', ...
    ['Bakker, D. C. E., Pfeil, B., Landa, C. S., Metzl, N., O''Brien, K. M., Olsen, A., Smith, K., Cosca, C., '...
    'Harasawa, S., Jones, S. D., Nakaoka, S.-I., Nojiri, Y., Schuster, U., Steinhoff, T., Sweeney, C., Takahashi, T., '...
    'Tilbrook, B., Wada, C., Wanninkhof, R., Alin, S. R., Balestrini, C. F., Barbero, L., Bates, N. R., Bianchi, A. A., ',...
    'Bonou, F., Boutin, J., Bozec, Y., Burger, E. F., Cai, W.-J., Castle, R. D., Chen, L., Chierici, M., Currie, K., ',...
    'Evans, W., Featherstone, C., Feely, R. A., Fransson, A., Goyet, C., Greenwood, N., Gregor, L., Hankin, S., ',...
    'Hardman-Mountford, N. J., Harlay, J., Hauck, J., Hoppema, M., Humphreys, M. P., Hunt, C. W., Huss, B., ',...
    'Ibánhez, J. S. P., Johannessen, T., Keeling, R., Kitidis, V., Körtzinger, A., Kozyr, A., Krasakopoulou, E., Kuwata, A., ',...
    'Landschützer, P., Lauvset, S. K., Lefèvre, N., Lo Monaco, C., Manke, A., Mathis, J. T., Merlivat, L., Millero, F. J., ',...
    'Monteiro, P. M. S., Munro, D. R., Murata, A., Newberger, T., Omar, A. M., Ono, T., Paterson, K., Pearce, D., Pierrot, D., ',...
    'Robbins, L. L., Saito, S., Salisbury, J., Schlitzer, R., Schneider, B., Schweitzer, R., Sieger, R., Skjelvan, I., ',...
    'Sullivan, K. F., Sutherland, S. C., Sutton, A. J., Tadokoro, K., Telszewski, M., Tuma, M., van Heuven, S. M. A. C., ',...
    'Vandemark, D., Ward, B., Watson, A. J., and Xu, S.: A multi-decade record of high-quality fCO2 data ',...
    'in version 3 of the Surface Ocean CO2 Atlas (SOCAT). Earth Syst. Sci. Data, 8, 383-413, doi:10.5194/essd-8-383-2016']);
    
netcdf.putAtt(ncid, globid, 'Citation_SOCATv6_Dataset', ['Bakker, Dorothee C E; Lauvset, Siv K; Wanninkhof, Rik; Castaño-Primo, Rocío; ',...
    'Currie, Kim I; Jones, Stephen D; Landa, Camilla S; Metzl, Nicolas; Nakaoka, Shin-Ichiro; Nojiri, Yukihiro; ',...
    'Nonaka, Isao; O''Brien, Kevin M; Olsen, Are; Pfeil, Benjamin; Pierrot, Denis; Schuster, Ute; Smith, Karl; ',...
    'Sullivan, Kevin; Sutton, Adrienne; Tilbrook, Bronte; Alin, Simone; Becker, Meike; Benoit-Cattin, Alice; ',...
    'Bott, Randy; Bozec, Yann; Bozzano, Roberto; Burger, Eugene; Burgers, Tonya; Cai, Wei-Jun; Chen, Liqi; ',...
    'Chierici, Melissa; Corredor, Jorge; Cosca, Catherine E; Cross, Jessica; Dandonneau, Yves; De Carlo, Eric Heinen; ',...
    'Dietrich, Colin; Else, Brent; Emerson, Steven R; Farias, Laura; Fransson, Agneta; Garreaud, René D; Gkritzalis, Thanos; ',...
    'Glockzin, Michael; González-Dávila, Melchor; Gregor, Luke; Hartman, Sue E; Hermes, Rudolf; Hoppema, Mario; Howden, Stephan; ',...
    'Hunt, Christopher W; Hydes, David; Ibánhez, J Severino P; Kitidis, Vassilis; Körtzinger, Arne; Kozyr, Alexander; ',...
    'Kuwata, Akira; Lampitt, Richard Stephen; Lefèvre, Nathalie; Lo Monaco, Claire; Maenner, Stacy M; Manke, Ansley; ',...
    'Manzello, Derek P; McGillis, Wade; Mickett, John; Monteiro, Pedro M S; Morell, Julio; Morrison, Ru; Mucci, Alfonso; ',...
    'Munro, David R; Musielewicz, Sylvia; Negri, Ruben M; Newberger, Timothy; Newton, Jan; Noakes, Scott; O''Brien, Chris; ',...
    'Ólafsdóttir, Sólveig Rósa; Ólafsson, Jón; Ono, Tsuneo; Osborne, John; Ouyang, Zhangxian; Padín, Xose Antonio; Papakyriakou, Tim N; ',...
    'Plüddemann, Albert J; Rehder, Gregor; Sabine, Christopher L; Sakurai, Keizo; Salisbury, Joe; Santana-Casiano, Juana Magdalena; ',...
    'Schlitzer, Reiner; Schneider, Bernd; Send, Uwe; Skjelvan, Ingunn; Steinhoff, Tobias; Sulpis, Olivier; Sutherland, Stewart C; ',...
    'Sweeney, Colm; Tadokoro, Kazuaki; Takahashi, Taro; Telszewski, Maciej; Thomas, Helmuth; Tomlinson, Michael; Trull, Tom W; ',...
    'Valdimarsson, Hedinn; van Heuven, Steven; Vandemark, Doug; Wada, Chisato; Wallace, Douglas WR; Watson, Andrew J; Weller, Robert A; Xu, Suqing',...
    'Surface Ocean CO2 Atlas (SOCAT) V6. PANGAEA, doi:10.1594/PANGAEA.890974']);

netcdf.close(ncid);

end

system(['cd /Users/rpr061/Dropbox/BCDC_Projects/CMEMS_INSTAC/REP_Products/current_FormatChecker/; for f in ', outdir,'*.nc; do ./control.csh $f >> ',outdir,'formatcheckoutSOCATgrid; done'])
