clc; 
clearvars -except SOCAT GLODAP
%clear all; 

close all
workrootdir=...
    '/Users/rpr061/Documents/localtestarea/CARBON-REP-122021/';
outdir=[workrootdir,'GLODAP_REP_OBSERVATIONS/'];
mkdir(outdir, 'VESSEL')
mkdir(outdir, 'ETC')

% Load GLODAP matlab file (generated by them)
GLODAP=load([workrootdir,'GLODAPv2.2021_Merged_Master_File.mat']);

%GLODAPv22019=load([workrootdir,'../original_files/GLODAPv2.2019_Merged_Master_File.mat']);

% Change all -9999 with NaN in GLODAP file
fn=fieldnames(GLODAP);
for nfn=1:length(fn)
    if ~iscell(GLODAP.(fn{nfn}))
        GLODAP.(fn{nfn})(GLODAP.(fn{nfn})==-9999)=NaN; end
end
% Some data points have NaN hour/minute
GLODAP.G2hour(isnan(GLODAP.G2hour))=0;
GLODAP.G2minute(isnan(GLODAP.G2minute))=0;

% Read the cruise/platform info sheet
%GLODAP_info=tdfread(['/Users/rpr061/Downloads/GLODAPv22021CMEMS.tsv']);
file=fopen([workrootdir,'GLODAPv22021CMEMS.tsv'],'r','n','UTF-8');
header=fgets(file);
header=strsplit(header,'\t');
header{end}=header{end}(1:end-2);
data=textscan(file, [repmat('%s',1,11),'%s\r'], 'Delimiter','\t');
fclose(file)
% Create structure
for ff=1:length(header);
    GLODAP_info.(header{ff})=data{ff}; end
GLODAP_info.CruiseCounter=cellfun(@str2num,GLODAP_info.CruiseCounter);

% Convert all char and numeric (except the CruiseCounter) fields to cellstr
fn=fieldnames(GLODAP_info);
for f=1:length(fn)
    if ischar(GLODAP_info.(fn{f})); GLODAP_info.(fn{f})=cellstr(GLODAP_info.(fn{f}));
    elseif isnumeric(GLODAP_info.(fn{f})) & ~strcmp(fn{f},'CruiseCounter')
        GLODAP_info.(fn{f})=cellstr(num2str(GLODAP_info.(fn{f})));
    end
end

%%
% Use the platform name as platform code if the callsign is missing
nocallsign=cellfun(@isempty,GLODAP_info.CallSign_WMO);
allplatformcodes=GLODAP_info.CallSign_WMO;
allplatformcodes(nocallsign)=GLODAP_info.Name(nocallsign);
% List of platforms (basis for splitting data in INSTAC)
unique_platform_code=unique(allplatformcodes);

% Variables names lists
% GLODAP variable (structure fields) names, with G2 prepended
invars={'bottomdepth','temperature','salinity','oxygen','nitrate',...
    'nitrite','phosphate','silicate','phtsinsitutp','phts25p0','tco2',...
    'talk','doc','don','tdn','chla'};
% GLODAP WOCE flag variable names, with G2 prepended. qc variables are
% secondary QC flags, not applicable (adjusted/unadjusted, etc)
flaggedvars={'salinityf','oxygenf','nitratef',...
    'nitritef','phosphatef','silicatef','phtsinsitutpf','phts25p0f','tco2f',...
    'talkf','docf','donf','tdnf','chlaf'};
% INSTAC variable names
osvars={'BATH','TEMP','PSAL','DOX2','NTAW',...
    'NTIW','PHOW','SLCW','PHPH','PH25','TICW',...
    'ALKW','CORG','NODW','NT1D','CPHL'};
% INSTAC units
osunits={'m','degrees_C','0.001','µmol kg-1','µmol kg-1',...
    'µmol kg-1','µmol kg-1','µmol kg-1','1','1','µmol kg-1',...
    'µmol kg-1','µmol kg-1','µmol kg-1','µmol kg-1','mg m-3'};
% INSTAC long name
oslongname={'Bathymetric depth','Sea temperature','Practical salinity',...
    'Dissolved oxygen','Nitrate (NO3-N)',...
    'Nitrite (NO2-N)','Phosphate (PO4-P)','Silicate (SIO4-SI)',...
    'Ph','Ph at 25 °C and 0 dbar','Dissolved inorganic carbon',...
    'Total alkalinity','Dissolved organic carbon','Dissolved organic nitrogen',...
    'Total dissolved nitrogen','Chlorophyll-a'};
% INSTAC standard name
osstandardname={'sea_floor_depth_below_sea_surface','sea_water_temperature',...
    'sea_water_practical_salinity','moles_of_oxygen_per_unit_mass_in_sea_water',...
    'moles_of_nitrate_per_unit_mass_in_sea_water','moles_of_nitrite_per_unit_mass_in_sea_water',...
    'moles_of_phosphate_per_unit_mass_in_sea_water','moles_of_silicate_per_unit_mass_in_sea_water',...
    'sea_water_ph_reported_on_total_scale',' ',...
    ' ','sea_water_alkalinity_per_unit_mass',...
    'moles_of_dissolved_organic_carbon_per_unit_mass_in_sea_water',' ',...
    'moles_of_dissolved_total_nitrogen_per_unit_mass_in_sea_water','mass_concentration_of_chlorophyll_a_in_sea_water'};

% Map GLODAP flags to OceanSITES: NaN -> 0; 0->8; 1->9; 2->1; 3->2; 4->4;
% 5->9; 6->8; 7->0; 8->0; 9->9
for nfv=1:length(flaggedvars)
    GLODAP.(['G2',flaggedvars{nfv}])(GLODAP.(['G2',flaggedvars{nfv}])==0)=8;
    GLODAP.(['G2',flaggedvars{nfv}])(GLODAP.(['G2',flaggedvars{nfv}])==1)=9;
    GLODAP.(['G2',flaggedvars{nfv}])(GLODAP.(['G2',flaggedvars{nfv}])==2)=1;
    GLODAP.(['G2',flaggedvars{nfv}])(GLODAP.(['G2',flaggedvars{nfv}])==3)=2;
    GLODAP.(['G2',flaggedvars{nfv}])(GLODAP.(['G2',flaggedvars{nfv}])==4)=4;
    GLODAP.(['G2',flaggedvars{nfv}])(GLODAP.(['G2',flaggedvars{nfv}])==5)=9;
    GLODAP.(['G2',flaggedvars{nfv}])(GLODAP.(['G2',flaggedvars{nfv}])==6)=8;
    GLODAP.(['G2',flaggedvars{nfv}])(GLODAP.(['G2',flaggedvars{nfv}])==7)=0;
    GLODAP.(['G2',flaggedvars{nfv}])(GLODAP.(['G2',flaggedvars{nfv}])==8)=0;
    GLODAP.(['G2',flaggedvars{nfv}])(GLODAP.(['G2',flaggedvars{nfv}])==9)=9;
    GLODAP.(['G2',flaggedvars{nfv}])=int8(GLODAP.(['G2',flaggedvars{nfv}]));
end

% Temperature and bottom depth are assumed good if they exist
GLODAP.G2bottomdepthf=zeros(size(GLODAP.G2salinityf));
GLODAP.G2temperaturef=ones(size(GLODAP.G2salinityf));


% NetCDF format specs
cmode = netcdf.getConstant('NETCDF4');
cmode = bitor(cmode,netcdf.getConstant('CLASSIC_MODEL'));
% Global attributes
data_type='OceanSITES vertical profile';
cdm_data_type='profile';

%%
tic


%% Only the wrong files
%wrongplatst=tdfread([outdir,'errorfiles'])
%wrongplats=wrongplatst.col1;
%wrongplats=cellstr(wrongplats)
%for ww=1:length(wrongplats); iwrong(ww)=find(ismember(unique_platform_code,wrongplats(ww))); end

% Either fix the issue of missing cruises or add the multiple ship cruises
%for platnum=[59,86,89,121];
for platnum=23%:length(unique_platform_code)
    
    currentpc=unique_platform_code{platnum};
    % All expocodes with same platform
    filterec=ismember(allplatformcodes,{currentpc});
    % All data from the expocodes with same platform
    filterdata=ismember(GLODAP.G2cruise,GLODAP_info.CruiseCounter(filterec));
    
    % Platform-specific global attributes in proper format
    % Platform attributes
    platform_code=char(unique(allplatformcodes(filterec)));
    platform_code=platform_code(isstrprop(platform_code, 'alphanum')); % remove not-allowed characters
    platform_name=char(unique(GLODAP_info.Name(filterec)));
    wmo_platform_code=char(unique(GLODAP_info.CallSign_WMO(filterec)));
    ices_platform_code=char(unique(GLODAP_info.ICEScode(filterec)));
        if isempty(wmo_platform_code); wmo_platform_code=' '; end
    if isempty(ices_platform_code); ices_platform_code=' '; end

        % Institution attributes
        
            % List of institutions
    institution=strjoin(transpose(unique(GLODAP_info.Institution(filterec))),'/');
    institution_edmo_code=regexprep(char(join(transpose(unique(GLODAP_info.EDMO(filterec))))),' +',' ');
        if contains(institution_edmo_code, 'NaN'); institution_edmo_code=''; end
    pi_institution=strjoin(transpose(unique(GLODAP_info.PI_Institution(filterec))),'/');
    %pi_institution_edmo_code=regexprep(char(join(transpose(unique(GLODAP_info.PI_EDMO(filterec))))),' +',' ');
     pi_institution_edmo_code=regexprep(char(join(transpose(unique(GLODAP_info.PI_EDMO(filterec))))),' +',' ');
           if contains(pi_institution_edmo_code, 'NaN'); pi_institution_edmo_code=''; end

     %allinstitution=[institution,';',pi_institution];
   if ~strcmp(institution_edmo_code,pi_institution_edmo_code)
           allinstitution=[institution,pi_institution];
    allinstitution_edmo_code=[institution_edmo_code,pi_institution_edmo_code];
   else allinstitution_edmo_code=[institution_edmo_code];
           allinstitution=[institution];
   end
      if strcmp(allinstitution_edmo_code(1),' '); allinstitution_edmo_code=allinstitution_edmo_code(2:end); end 

   % List of PIs
    allpis=unique(GLODAP_info.PI(filterec));
    for aa=1:length(allpis)
    indpi{aa}=strsplit(allpis{aa},','); end
    pis=strjoin(unique([indpi{:}]),';');         
%         
%     institution=strjoin(transpose(unique(GLODAP_info.Institution(filterec))),'/');
%     institution_edmo_code=regexprep(char(join(transpose(unique(GLODAP_info.EDMO(filterec))))),' +',' ');
%     if strcmp(institution_edmo_code, " NaN"); institution_edmo_code=''; end
%     pi_institution=strjoin(transpose(unique(GLODAP_info.PI_Institution(filterec))),'/');
%     pi_institution_edmo_code=regexprep(char(join(transpose(unique(GLODAP_info.PI_EDMO(filterec))))),' +',' ');
%     pis=strjoin(transpose(unique(GLODAP_info.CarbonPI(filterec))),'/');
%     
    source_platform_category_code=char(unique(GLODAP_info.PlatformType(filterec)));
    switch source_platform_category_code
        case '31'
            source='research vessel';
            outputfile = ['VESSEL/GL_PR_BO_',platform_code,'-GLODAPv22021.nc'];
        case '21'
            source='propelled manned submersible';
            outputfile = ['ETC/GL_PR_BO_',platform_code,'-GLODAPv22021.nc'];
        case '62'
            source='aeroplane';
            outputfile = ['ETC/GL_PR_BO_',platform_code,'-GLODAPv22021.nc'];
    end
    splitoutfile=split(outputfile,'/');
    identifier=splitoutfile{2}(1:end-3);

    
    % Dimensions: TIME DEPTH
    % Read (and reformat) GLODAP time and depth.
    depthinglodap=GLODAP.G2depth(filterdata); % data only from the relevant cruises
    [daa,dbb,dcc]=unique(depthinglodap); % string of unique depth values
    
    timeinglodapMATLAB = datenum(([GLODAP.G2year(filterdata),...
        GLODAP.G2month(filterdata),GLODAP.G2day(filterdata),...
        GLODAP.G2hour(filterdata),GLODAP.G2minute(filterdata),...
        zeros(size(GLODAP.G2minute(filterdata)))]));
    timeinglodap = timeinglodapMATLAB - datenum('1950-01-01T00:00:00Z','yyyy-mm-ddTHH:MM:SSZ');
    [taa,tbb,tcc]=unique(timeinglodap);
    
    % Create DEPH variable and QC matrices
    dephinmatrix=nan(length(daa),length(taa));
    dephinqcmatrix=nan(length(daa),length(taa));
    
    for oo=1:length(depthinglodap)
        dephinmatrix(dcc(oo),tcc(oo))=mean(depthinglodap(oo),'omitnan');
        dephinqcmatrix(dcc(oo),tcc(oo))=1;
    end
    
    latinglodap = GLODAP.G2latitude(filterdata);
    latin=latinglodap(tbb);
    loninglodap=GLODAP.G2longitude(filterdata);
    lonin=loninglodap(tbb);
    
    % Variables
    for vv=1:length(invars)
        % Data from the relevant cruises
        eval([invars{vv},'inglodap=round(GLODAP.',['G2',invars{vv}],'(filterdata)*1000.);']);
        eval([invars{vv},'finglodap=GLODAP.',['G2',invars{vv}],'f(filterdata);']);
        
        % Preallocate depthxtime matrices
        eval([invars{vv},'in=nan(length(daa),length(taa));']);
        eval([invars{vv},'inqc=nan(length(daa),length(taa));']);
        
        % Fill depthxtime matrices
        for oo=1:length(depthinglodap)
            % For cases of 2 measurements at the same point (e.g. two
            % bottles sampled: calculate "cumulatively" the average)
            eval([invars{vv},'in(dcc(oo),tcc(oo))=round(mean([',...
                invars{vv},'in(dcc(oo),tcc(oo)),',...
                invars{vv},'inglodap(oo)],''omitnan''));']);
            
            % If value is average of >1 bottle, flag is 8 (interpolated)
            if  eval(['isnan(',invars{vv},'inqc(dcc(oo),tcc(oo)));'])
                
                eval([invars{vv},'inqc(dcc(oo),tcc(oo))=',invars{vv},'finglodap(oo);']);
            else
                eval([invars{vv},'inqc(dcc(oo),tcc(oo))=8;']);
            end
            
        end
        eval([invars{vv},'in(isnan(',invars{vv},'in))=-2147483647;']);
        eval([invars{vv},'inqc(isnan(',invars{vv},'inqc))=-127;']);
    end
    
    daa(isnan(daa))=9.9692099683868690e+36;
    dephinqc=ones(size(daa));
    timeinqc=ones(size(taa));
    posinqc=ones(size(taa));
    
    %% Generate NetCDF
    % Create NetCDF file
    if exist([outdir,outputfile]); delete([outdir,outputfile]);end
    ncid = netcdf.create([outdir,outputfile], cmode);
    
    % Define dimensions and variables
    % Define dimensions
    latdim = netcdf.defDim(ncid, 'LATITUDE', length(latin));
    londim = netcdf.defDim(ncid, 'LONGITUDE', length(lonin));
    posdim = netcdf.defDim(ncid, 'POSITION', length(lonin));
    timedim = netcdf.defDim(ncid, 'TIME', length(taa));
    depthdim = netcdf.defDim(ncid, 'DEPTH', length(daa));
    
    % Define dimension-ish variables
    latvar = netcdf.defVar(ncid, 'LATITUDE', 'NC_FLOAT', latdim);
    lonvar = netcdf.defVar(ncid, 'LONGITUDE', 'NC_FLOAT', londim);
    timevar = netcdf.defVar(ncid, 'TIME', 'NC_DOUBLE', timedim);
    dephvar = netcdf.defVar(ncid, 'DEPH', 'NC_FLOAT', [depthdim,timedim]);
    
    % Dimension variables QC DM
    dephvarqc = netcdf.defVar(ncid, 'DEPH_QC', 'NC_BYTE', [depthdim,timedim]);
    posvarqc = netcdf.defVar(ncid, 'POSITION_QC', 'NC_BYTE', posdim);
    timevarqc = netcdf.defVar(ncid, 'TIME_QC', 'NC_BYTE', timedim);
    
    % Define other variables
    for vv=1:length(invars)
        eval([invars{vv},'var=netcdf.defVar(ncid,''',osvars{vv},...
            ''',''NC_INT'',[depthdim,timedim]);']);
        eval([invars{vv},'varqc=netcdf.defVar(ncid,''',osvars{vv},...
            '_QC'',''NC_BYTE'',[depthdim,timedim]);']);
    end
    
%     % Define _FillValue (does not work after reDef);
    netcdf.defVarFill(ncid, timevar, false, 9.9692099683868690e+36);
    netcdf.defVarFill(ncid, latvar, false, 9.9692099683868690e+36);
    netcdf.defVarFill(ncid, lonvar, false, 9.9692099683868690e+36);
    netcdf.defVarFill(ncid, dephvar, false, 9.9692099683868690e+36);
    netcdf.defVarFill(ncid, timevarqc, false, -127);
    netcdf.defVarFill(ncid, posvarqc, false, -127);
    netcdf.defVarFill(ncid, dephvarqc, false, -127);
    
    for vv=1:length(invars)
        eval(['netcdf.defVarFill(ncid,',invars{vv},'var,false,-2147483647);']);
        eval(['netcdf.defVarFill(ncid,',invars{vv},'varqc,false,-127);']);
    end
    
    % Exit define mode
    netcdf.endDef(ncid);
    
    % Put data
    % Put data in dimensions
    netcdf.putVar(ncid, latvar, latin);
    netcdf.putVar(ncid, lonvar, lonin);
    netcdf.putVar(ncid, timevar, taa);
    netcdf.putVar(ncid, timevarqc, timeinqc);
    netcdf.putVar(ncid, dephvar, dephinmatrix);
    netcdf.putVar(ncid, dephvarqc, dephinqcmatrix);
    netcdf.putVar(ncid, posvarqc, posinqc);
    
    % Put data in variables
    for vv=1:length(invars);
        eval(['netcdf.putVar(ncid,',invars{vv},'var,',invars{vv},'in);']);
        eval(['netcdf.putVar(ncid,',invars{vv},'varqc,',invars{vv},'inqc);']);
    end
    
    % Re-enter define mode (can be done before???)
    netcdf.reDef(ncid);
    
    % Add attributes
     % Add attributes to dimensions
    netcdf.putAtt(ncid, latvar, 'long_name', 'Latitude of each location');
    netcdf.putAtt(ncid, latvar, 'standard_name', 'latitude');
    netcdf.putAtt(ncid, latvar, 'units', 'degree_north');
    netcdf.putAtt(ncid, latvar, 'valid_min', -90.0);
    netcdf.putAtt(ncid, latvar, 'valid_max', 90.0);
    netcdf.putAtt(ncid, latvar, 'QC_indicator', int8(1));
    netcdf.putAtt(ncid, latvar, 'uncertainty', '');
    netcdf.putAtt(ncid, latvar, 'comment', '');
    netcdf.putAtt(ncid, latvar, 'axis', 'Y');
    netcdf.putAtt(ncid, latvar, 'ancillary_variables', 'POSITION_QC'); 
    netcdf.delAtt(ncid, latvar, '_FillValue'); 

    
    % Longitude
    netcdf.putAtt(ncid, lonvar, 'long_name', 'Longitude of each location');
    netcdf.putAtt(ncid, lonvar, 'standard_name', 'longitude');
    netcdf.putAtt(ncid, lonvar, 'units', 'degree_east');
    netcdf.putAtt(ncid, lonvar, 'valid_min', -180.0);
    netcdf.putAtt(ncid, lonvar, 'valid_max', 180.0);
    netcdf.putAtt(ncid, lonvar, 'QC_indicator', int8(1));
    netcdf.putAtt(ncid, lonvar, 'uncertainty', '');
    netcdf.putAtt(ncid, lonvar, 'comment', '');
    netcdf.putAtt(ncid, lonvar, 'axis', 'X');
    netcdf.putAtt(ncid, lonvar, 'ancillary_variables', 'POSITION_QC');
        netcdf.delAtt(ncid, lonvar, '_FillValue'); 

    % Time
    netcdf.putAtt(ncid, timevar, 'long_name', 'Time');
    netcdf.putAtt(ncid, timevar, 'standard_name', 'time');
    netcdf.putAtt(ncid, timevar, 'units', 'days since 1950-01-01T00:00:00Z');
    netcdf.putAtt(ncid, timevar, 'valid_min', -90000.);
    netcdf.putAtt(ncid, timevar, 'valid_max', 90000.);
    netcdf.putAtt(ncid, timevar, 'QC_indicator', int8(1));
    netcdf.putAtt(ncid, timevar, 'uncertainty', '');
    netcdf.putAtt(ncid, timevar, 'comment', '');
    netcdf.putAtt(ncid, timevar, 'axis', 'T');
    netcdf.putAtt(ncid, timevar, 'ancillary_variables', 'TIME_QC');
    netcdf.putAtt(ncid, timevar, 'calendar', 'standard');
    netcdf.delAtt(ncid, timevar, '_FillValue'); 

    
    % Depth
    netcdf.putAtt(ncid, dephvar, 'long_name', 'Depth');
    netcdf.putAtt(ncid, dephvar, 'standard_name', 'depth');
    netcdf.putAtt(ncid, dephvar, 'units', 'm');
    netcdf.putAtt(ncid, dephvar, 'positive', 'down');
    netcdf.putAtt(ncid, dephvar, 'valid_min', -12000.0);
    netcdf.putAtt(ncid, dephvar, 'valid_max', 12000.0);
    netcdf.putAtt(ncid, dephvar, 'uncertainty', '');
    netcdf.putAtt(ncid, dephvar, 'comment', '');
    netcdf.putAtt(ncid, dephvar, 'axis', 'Z');
    netcdf.putAtt(ncid, dephvar, 'reference', 'sea_level');
    netcdf.putAtt(ncid, dephvar, 'data_mode', 'D');
    netcdf.putAtt(ncid, dephvar, 'ancillary_variables', 'DEPH_QC');

    
    % Time QC
    attributes_qc(ncid,timevarqc); netcdf.putAtt(ncid, timevarqc, 'long_name', 'Time quality flag');
    attributes_qc(ncid,dephvarqc); netcdf.putAtt(ncid, dephvarqc, 'long_name', 'Depth quality flag');
    attributes_qc(ncid,posvarqc); netcdf.putAtt(ncid, posvarqc, 'long_name', 'Position quality flag');

    
    % Add attributes to variables
    for vv=1:length(invars)
        % Variables
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''standard_name'',''',osstandardname{vv},''');']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''units'',''',osunits{vv},''');']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''add_offset'',0);']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''scale_factor'',0.001);']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''long_name'',''',oslongname{vv},''');']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''valid_min'','' '');']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''valid_max'','' '');']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''coordinates'',''TIME LATITUDE LONGITUDE DEPH'');']);
        %eval(['netcdf.putAtt(ncid,',invars{vv},'var,''comment'','' '');']);
        %eval(['netcdf.putAtt(ncid,',invars{vv},'var,''uncertainty'','' '');']);
        %eval(['netcdf.putAtt(ncid,',invars{vv},'var,''accuracy'','' '');']);
        %eval(['netcdf.putAtt(ncid,',invars{vv},'var,''precision'','' '');']);
        %eval(['netcdf.putAtt(ncid,',invars{vv},'var,''resolution'','' '');']);
        %eval(['netcdf.putAtt(ncid,',invars{vv},'var,''cell_methods'','' '');']);
        %eval(['netcdf.putAtt(ncid,',invars{vv},'var,''type_of_analysis'','' '');']);
        %eval(['netcdf.putAtt(ncid,',invars{vv},'var,''sensor_depth'','' '');']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''sensor_mount'',''mounted_on_shipborne_profiler'');']);
        %eval(['netcdf.putAtt(ncid,',invars{vv},'var,''sensor_depth'','' '');']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''data_mode'',''D'');']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'var,''ancillary_variables'',','''',osvars{vv},'_QC'');']);
        % QC variables
        eval(['attributes_qc(ncid,',invars{vv},'varqc);']);
        eval(['netcdf.putAtt(ncid,',invars{vv},'varqc,''long_name'',','''',oslongname{vv},' quality flag'');']);
  %     eval(['netcdf.delAtt(ncid,',invars{vv},',''_FillValue'');']);

    end
    
    % Global attributes
    globid = netcdf.getConstant('GLOBAL');
    
        netcdf.putAtt(ncid, globid, 'platform_code', platform_code);
    netcdf.putAtt(ncid, globid, 'platform_name', platform_name);
    netcdf.putAtt(ncid, globid, 'data_mode', 'D');
    netcdf.putAtt(ncid, globid, 'title', 'Global Ocean - In Situ reprocessed carbon observations - GLODAPv2.2021');
    netcdf.putAtt(ncid, globid, 'summary', '');
    netcdf.putAtt(ncid, globid, 'naming_authority', 'Copernicus Marine In Situ');
    netcdf.putAtt(ncid, globid, 'id', identifier);
%if (strcmp(source_platform_category_code,'31') | strcmp(source_platform_category_code,'32')) & ~isempty(ices_platform_code)
        netcdf.putAtt(ncid, globid, 'wmo_platform_code', wmo_platform_code);
        netcdf.putAtt(ncid, globid, 'ices_platform_code', ices_platform_code);
%end

    netcdf.putAtt(ncid, globid, 'source', source);
    netcdf.putAtt(ncid, globid, 'source_platform_category_code', source_platform_category_code);
    netcdf.putAtt(ncid, globid, 'institution_edmo_code', allinstitution_edmo_code);
    netcdf.putAtt(ncid, globid, 'institution', allinstitution);
    netcdf.putAtt(ncid, globid, 'institution_references', ' ');
    netcdf.putAtt(ncid, globid, 'site_code', ''); %OceanSites code; e.g. STATION-M
    netcdf.putAtt(ncid, globid, 'comment', ' '); 
    netcdf.putAtt(ncid, globid, 'contact', 'data.manager@bcdc.no cmems-service@ifremer.fr'); 

    netcdf.putAtt(ncid, globid, 'area', 'Global');     
    netcdf.putAtt(ncid, globid, 'geospatial_lat_min', num2str(min(latin)));
    netcdf.putAtt(ncid, globid, 'geospatial_lat_max', num2str(max(latin)));
    netcdf.putAtt(ncid, globid, 'geospatial_lon_min', num2str(min(lonin)));
    netcdf.putAtt(ncid, globid, 'geospatial_lon_max', num2str(max(lonin)));
    netcdf.putAtt(ncid, globid, 'geospatial_vertical_min', min(dephvar));
    netcdf.putAtt(ncid, globid, 'geospatial_vertical_max', max(dephvar));
    netcdf.putAtt(ncid, globid, 'time_coverage_start', datestr(min(timeinglodapMATLAB),'yyyy-mm-ddTHH:MM:SSZ'));
    netcdf.putAtt(ncid, globid, 'time_coverage_end', datestr(max(timeinglodapMATLAB),'yyyy-mm-ddTHH:MM:SSZ'));
    netcdf.putAtt(ncid, globid, 'cdm_data_type', cdm_data_type);
    netcdf.putAtt(ncid, globid, 'data_type', data_type);
    netcdf.putAtt(ncid, globid, 'bottom_depth', ' ');

    netcdf.putAtt(ncid, globid, 'format_version', '1.4');
    netcdf.putAtt(ncid, globid, 'Conventions', 'CF-1.6 Copernicus-InSituTAC-FormatManual-1.42 Copernicus-InSituTAC-SRD-1.5 Copernicus-InSituTAC-ParametersList-3.2.0');
    netcdf.putAtt(ncid, globid, 'netcdf_version', 'netCDF-4 classic model');
    netcdf.putAtt(ncid, globid, 'references', 'http://marine.copernicus.eu http://www.marineinsitu.eu https://www.glodap.info');
    netcdf.putAtt(ncid, globid, 'data_assembly_center', 'University of Bergen');
    netcdf.putAtt(ncid, globid, 'update_interval', 'P1Y');
    
        netcdf.putAtt(ncid, globid, 'citation', ['These data were collected and made freely available by the Copernicus project and the programs that contribute to it. ',...
        'GLODAPv2.2021 is described in Lauvset et al. (2021)a, and Lauvset et al. (2021)b; traceable citations are essential for justifying and sustaining the effort.']);
    netcdf.putAtt(ncid, globid, 'distribution_statement',['These data follow Copernicus standards; they are public ',...
        'and free of charge. User assumes all risk for use of data. User must display citation in any publication or ',...
        'product using data. User must contact PI prior to any commercial use of data.']);
    
    netcdf.putAtt(ncid, globid, 'doi', 'https://doi.org/10.25921/ttgq-n825 https://doi.org/10.5194/essd-2021-234');
    netcdf.putAtt(ncid, globid, 'pi_name', pis);
    netcdf.putAtt(ncid, globid, 'qc_manual', '');
    
    netcdf.putAtt(ncid, globid, 'date_update', datestr(now, 'yyyy-mm-ddTHH:MM:SSZ'));
    netcdf.putAtt(ncid, globid, 'history', [datestr(now, 'yyyy-mm-ddTHH:MM:SSZ'),' : Creation']);
    netcdf.putAtt(ncid, globid, 'last_date_observation',datestr(timeinglodapMATLAB(end),'yyyy-mm-ddTHH:MM:SSZ'));
    netcdf.putAtt(ncid, globid, 'last_latitude_observation',latin(end));
    netcdf.putAtt(ncid, globid, 'last_longitude_observation',lonin(end));
    netcdf.putAtt(ncid, globid, 'wmo_inst_type', '');
    
    % Close nc file
    netcdf.close(ncid);
    
    % Clear variables
    clearvars '-except' workrootdir outdir GLODAP GLODAP_info ...
        cmode allplatformcodes unique_platform_code platnum ...
        invars vars osvars osunits oslongname osstandardname ...
        data_type cdm_data_type
end

toc
%%
% Pass the format checker through all the files
%system(['cd /Users/rpr061/Dropbox/BCDC_projects/CMEMS_INSTAC/Releases/current_FormatChecker; for f in ', outdir,'VESSEL/*.nc; do ./control.csh $f >> ',outdir,'VESSEL_formatcheckoutSOCAT; done'])
%system(['cd /Users/rpr061/Dropbox/BCDC_projects/CMEMS_INSTAC/Releases/current_FormatChecker; for f in ', outdir,'ETC/*.nc; do ./control.csh $f >> ',outdir,'ETC_formatcheckoutSOCAT; done'])


%% ============= FUNCTIONS ================================================
function attributes_qc(ncid, inputvar)
%netcdf.putAtt(ncid, inputvar, 'long_name', 'quality flag');
netcdf.putAtt(ncid, inputvar, 'conventions', 'Copernicus Marine In Situ reference table 2');
netcdf.putAtt(ncid, inputvar, 'valid_min', int8(0));
netcdf.putAtt(ncid, inputvar, 'valid_max', int8(9));
netcdf.putAtt(ncid, inputvar, 'flag_values',  [int8(0)  int8(1)  int8(2)  int8(3)  int8(4)  int8(5)  int8(6)  int8(7)  int8(8)  int8(9)]);
netcdf.putAtt(ncid, inputvar, 'flag_meanings','no_qc_performed good_data probably_good_data bad_data_that_are_potentially_correctable bad_data value_changed value_below_detection nominal_value interpolated_value missing_value');

end



