clc; clear all; close all
workrootdir='/Users/rpr061/Dropbox/BCDC_Projects/CMEMS_INSTAC/REP_Products/';

%% Import data from text file.
% Script for importing data from the GLODAPv2 Merged Master File.csv file
% Auto-generated by MATLAB on 2019/02/05 06:08:04
% Edited by RCP 2019-02-27

%% Initialize variables.
filename = [workrootdir,'2018/GLODAPv2/original/GLODAPv2 Merged Master File.csv'];
delimiter = ',';
startRow = 2;

%% Format for each line of text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
GLODAPv2.cruise = dataArray{:, 1};
GLODAPv2.station = dataArray{:, 2};
GLODAPv2.cast1 = dataArray{:, 3};
GLODAPv2.year1 = dataArray{:, 4};
GLODAPv2.month1 = dataArray{:, 5};
GLODAPv2.day1 = dataArray{:, 6};
GLODAPv2.hour1 = dataArray{:, 7};
GLODAPv2.minute1 = dataArray{:, 8};
GLODAPv2.latitude = dataArray{:, 9};
GLODAPv2.longitude = dataArray{:, 10};
GLODAPv2.bottomdepth = dataArray{:, 11};
GLODAPv2.maxsampdepth = dataArray{:, 12};
GLODAPv2.bottle = dataArray{:, 13};
GLODAPv2.pressure = dataArray{:, 14};
GLODAPv2.depth = dataArray{:, 15};
GLODAPv2.temperature = dataArray{:, 16};
GLODAPv2.theta = dataArray{:, 17};
GLODAPv2.salinity = dataArray{:, 18};
GLODAPv2.salinityf = dataArray{:, 19};
GLODAPv2.salinityqc = dataArray{:, 20};
GLODAPv2.sigma0 = dataArray{:, 21};
GLODAPv2.sigma1 = dataArray{:, 22};
GLODAPv2.sigma2 = dataArray{:, 23};
GLODAPv2.sigma3 = dataArray{:, 24};
GLODAPv2.sigma4 = dataArray{:, 25};
GLODAPv2.gamma1 = dataArray{:, 26};
GLODAPv2.oxygen = dataArray{:, 27};
GLODAPv2.oxygenf = dataArray{:, 28};
GLODAPv2.oxygenqc = dataArray{:, 29};
GLODAPv2.aou = dataArray{:, 30};
GLODAPv2.aouf = dataArray{:, 31};
GLODAPv2.nitrate = dataArray{:, 32};
GLODAPv2.nitratef = dataArray{:, 33};
GLODAPv2.nitrateqc = dataArray{:, 34};
GLODAPv2.nitrite = dataArray{:, 35};
GLODAPv2.nitritef = dataArray{:, 36};
GLODAPv2.silicate = dataArray{:, 37};
GLODAPv2.silicatef = dataArray{:, 38};
GLODAPv2.silicateqc = dataArray{:, 39};
GLODAPv2.phosphate = dataArray{:, 40};
GLODAPv2.phosphatef = dataArray{:, 41};
GLODAPv2.phosphateqc = dataArray{:, 42};
GLODAPv2.tco2 = dataArray{:, 43};
GLODAPv2.tco2f = dataArray{:, 44};
GLODAPv2.tco2qc = dataArray{:, 45};
GLODAPv2.talk = dataArray{:, 46};
GLODAPv2.talkf = dataArray{:, 47};
GLODAPv2.talkqc = dataArray{:, 48};
GLODAPv2.phts25p0 = dataArray{:, 49};
GLODAPv2.phts25p0f = dataArray{:, 50};
GLODAPv2.phtsinsitutp = dataArray{:, 51};
GLODAPv2.phtsinsitutpf = dataArray{:, 52};
GLODAPv2.phtsqc = dataArray{:, 53};
GLODAPv2.cfc11 = dataArray{:, 54};
GLODAPv2.pcfc11 = dataArray{:, 55};
GLODAPv2.cfc11f = dataArray{:, 56};
GLODAPv2.cfc11qc = dataArray{:, 57};
GLODAPv2.cfc12 = dataArray{:, 58};
GLODAPv2.pcfc12 = dataArray{:, 59};
GLODAPv2.cfc12f = dataArray{:, 60};
GLODAPv2.cfc12qc = dataArray{:, 61};
GLODAPv2.cfc113 = dataArray{:, 62};
GLODAPv2.pcfc113 = dataArray{:, 63};
GLODAPv2.cfc113f = dataArray{:, 64};
GLODAPv2.cfc113qc = dataArray{:, 65};
GLODAPv2.ccl4 = dataArray{:, 66};
GLODAPv2.pccl4 = dataArray{:, 67};
GLODAPv2.ccl4f = dataArray{:, 68};
GLODAPv2.ccl4qc = dataArray{:, 69};
GLODAPv2.sf6 = dataArray{:, 70};
GLODAPv2.psf6 = dataArray{:, 71};
GLODAPv2.sf6f = dataArray{:, 72};
GLODAPv2.c13 = dataArray{:, 73};
GLODAPv2.c13f = dataArray{:, 74};
GLODAPv2.c14 = dataArray{:, 75};
GLODAPv2.c14f = dataArray{:, 76};
GLODAPv2.c14err = dataArray{:, 77};
GLODAPv2.h3 = dataArray{:, 78};
GLODAPv2.h3f = dataArray{:, 79};
GLODAPv2.h3err = dataArray{:, 80};
GLODAPv2.he3 = dataArray{:, 81};
GLODAPv2.he3f = dataArray{:, 82};
GLODAPv2.he3err = dataArray{:, 83};
GLODAPv2.he = dataArray{:, 84};
GLODAPv2.hef = dataArray{:, 85};
GLODAPv2.heerr = dataArray{:, 86};
GLODAPv2.neon = dataArray{:, 87};
GLODAPv2.neonf = dataArray{:, 88};
GLODAPv2.neonerr = dataArray{:, 89};
GLODAPv2.o18 = dataArray{:, 90};
GLODAPv2.o18f = dataArray{:, 91};
GLODAPv2.toc1 = dataArray{:, 92};
GLODAPv2.tocf = dataArray{:, 93};
GLODAPv2.doc1 = dataArray{:, 94};
GLODAPv2.docf = dataArray{:, 95};
GLODAPv2.don = dataArray{:, 96};
GLODAPv2.donf = dataArray{:, 97};
GLODAPv2.tdn = dataArray{:, 98};
GLODAPv2.tdnf = dataArray{:, 99};
GLODAPv2.chla = dataArray{:, 100};
GLODAPv2.chlaf = dataArray{:, 101};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%% Save mat file
save([workrootdir,'2018/GLODAPv2/workspace/GLODAPv2.mat'], 'GLODAPv2');