clc; clear all; close all
workrootdir='/Users/rpr061/Dropbox/BCDC_Projects/CMEMS_INSTAC/REP_Products/';

%% Import data from text file.
% Script for importing data from the SOCATv6.tsv file, header removed.
% The SOCATv6 table with the full set of variables was >2GB.
% Since this is for Copernicus, we keep only the data needed (time,
% position, temperature, salinity, fCO2 in situ.
% Auto-generated by MATLAB on 2019/02/04 20:03:50
% Edited by RCP 2019-02-27

%% Initialize variables.
filename = [workrootdir,'2018/SOCATv6/workspace/monsterfile2mat/SOCATv6_woheader.tsv'];
delimiter = '\t';
startRow = 2;

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%d%d%d%d%d%d%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%d%[^\n\r]';
fileID = fopen(filename,'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);

%% Allocate imported array to column variable names
SOCATv6.Expocode = categorical(dataArray{:, 1});
%SOCATv6.version1 = (dataArray{:, 2});
%SOCATv6.SOCAT_DOI = categorical(dataArray{:, 3});
%SOCATv6.QC_Flag = categorical(dataArray{:, 4});
SOCATv6.yr = (dataArray{:, 5});
SOCATv6.mon = (dataArray{:, 6});
SOCATv6.day1 = (dataArray{:, 7});
SOCATv6.hh = (dataArray{:, 8});
SOCATv6.mm = (dataArray{:, 9});
SOCATv6.ss = (dataArray{:, 10});
SOCATv6.longitudedecdegE = (dataArray{:, 11});
SOCATv6.latitudedecdegN = (dataArray{:, 12});
%SOCATv6.sample_depthm = (dataArray{:, 13});
SOCATv6.sal = (dataArray{:, 14});
SOCATv6.SSTdegC = (dataArray{:, 15});
%SOCATv6.TequdegC = (dataArray{:, 16});
%SOCATv6.PPPPhPa = (dataArray{:, 17});
%SOCATv6.PequhPa = (dataArray{:, 18});
%SOCATv6.WOA_SSS = (dataArray{:, 19});
%SOCATv6.NCEP_SLPhPa = (dataArray{:, 20});
%SOCATv6.ETOPO2_depthm = (dataArray{:, 21});
%SOCATv6.dist_to_landkm = (dataArray{:, 22});
%SOCATv6.GVCO2umolmol = (dataArray{:, 23});
SOCATv6.fCO2recuatm = (dataArray{:, 24});
%SOCATv6.fCO2rec_src = (dataArray{:, 25});
SOCATv6.fCO2rec_flag = (dataArray{:, 26});

dumExpocode=cellstr(SOCATv6.Expocode);


load([workrootdir,'2018/ReferenceData/PlatformCodes.mat']);

for ee=1:length(dumExpocode)
    SOCATv6.ICEScode{ee,1}=dumExpocode{ee}(1:4); 
    if any(ismember(ResearchVessels.SOCAT_code,...
            dumExpocode{ee}(1:4)))
       SOCATv6.PlatformName{ee,1}=ResearchVessels.Name{...
            ismember(ResearchVessels.SOCAT_code,...
            dumExpocode{ee}(1:4))};
        
    elseif any(ismember(ShipsofOpportunity.SOCAT_code,...
            dumExpocode{ee}(1:4)))
       SOCATv6.PlatformName{ee,1}=ShipsofOpportunity.Name{...
            ismember(ShipsofOpportunity.SOCAT_code,...
            dumExpocode{ee}(1:4))};
        
    elseif any(ismember(FixedMoorings.SOCAT_code,...
            dumExpocode{ee}))
       SOCATv6.PlatformName{ee,1}=FixedMoorings.Name{...
            ismember(FixedMoorings.SOCAT_code,...
            dumExpocode{ee})};
        
    elseif any(ismember(DriftingBuoys.SOCAT_code,...
            dumExpocode{ee}))
       SOCATv6.PlatformName{ee,1}=DriftingBuoys.Name{...
            ismember(DriftingBuoys.SOCAT_code,...
            dumExpocode{ee})}; 
    end
end
SOCATv6.ICEScode=categorical(SOCATv6.ICEScode);
SOCATv6.PlatformName=categorical(SOCATv6.PlatformName);

%% Add platform names (to tell appart moorings);

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp rawNumericColumns rawStringColumns R catIdx idx;

%% save as .mat file (shorten the time needed);
save([workrootdir,'2018/SOCATv6/workspace/SOCATv6.mat'], 'SOCATv6');