clc; clear all; close all
workrootdir=...
    '/Users/rpr061/Dropbox/BCDC_Projects/CMEMS_INSTAC/REP_Products/';

%% Import data from text file.
% Script for importing data from the Copernicus codes files
% Auto-generated by MATLAB on 2019/02/27 16:09:18
% Edited by RCP 2019-02-27

%% Research Vessls
filename = [workrootdir,...
    '04_2018/ReferenceData/Codes_for_Copernicus - Research_Vessels.tsv'];
delimiter = '\t';
startRow = 2;
formatSpec = '%s%s%s%s%s%s%[^\n\r]';
fileID = fopen(filename,'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);

ResearchVessels.SOCAT_code = cellstr(char(dataArray{1,1}(:)));
ResearchVessels.Name = cellstr(char(dataArray{1,2}(:)));
ResearchVessels.Callsign =cellstr(char(dataArray{1,3}(:)));
ResearchVessels.IMO = cellstr(char(dataArray{1,4}(:)));
ResearchVessels.EDMO =cellstr(char(dataArray{1,5}(:)));
ResearchVessels.Institute = cellstr(char(dataArray{1,6}(:)));

clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawNumericColumns rawStringColumns;

%% Ships of Opportunity
filename = [workrootdir,...
    '04_2018/ReferenceData/Codes_for_Copernicus - Ships_of_Opportunity.tsv'];
delimiter = '\t';
startRow = 2;
formatSpec = '%s%s%s%s%s%s%[^\n\r]';
fileID = fopen(filename,'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);

ShipsofOpportunity.SOCAT_code = cellstr(char(dataArray{1,1}(:)));
ShipsofOpportunity.Name = cellstr(char(dataArray{1,2}(:)));
ShipsofOpportunity.Callsign =cellstr(char(dataArray{1,3}(:)));
ShipsofOpportunity.IMO = cellstr(char(dataArray{1,4}(:)));
ShipsofOpportunity.EDMO =cellstr(char(dataArray{1,5}(:)));
ShipsofOpportunity.Institute = cellstr(char(dataArray{1,6}(:)));

clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawNumericColumns rawStringColumns;

%% Moorings
filename = [workrootdir,...
    '04_2018/ReferenceData/Codes_for_Copernicus - Fixed_moorings.tsv'];
delimiter = '\t';
startRow = 2;
formatSpec = '%s%s%s%s%s%s%[^\n\r]';
fileID = fopen(filename,'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);

FixedMoorings.SOCAT_code = cellstr(char(dataArray{1,1}(:)));
FixedMoorings.Name = cellstr(char(dataArray{1,2}(:)));
FixedMoorings.WMO =cellstr(char(dataArray{1,3}(:)));
FixedMoorings.OceanSITES = cellstr(char(dataArray{1,4}(:)));
FixedMoorings.EDMO =cellstr(char(dataArray{1,5}(:)));
FixedMoorings.Institute = cellstr(char(dataArray{1,6}(:)));

% Temp fix because it's one short
while length(FixedMoorings.OceanSITES)<length(FixedMoorings.SOCAT_code);
FixedMoorings.OceanSITES(length(FixedMoorings.OceanSITES)+1)={''};
end

clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawNumericColumns rawStringColumns;

%% Drifting buoys
filename = [workrootdir,...
    '04_2018/ReferenceData/Codes_for_Copernicus - Drifting_buoys.tsv'];
delimiter = '\t';
startRow = 2;
formatSpec = '%s%s%s%s%s%[^\n\r]';
fileID = fopen(filename,'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);

DriftingBuoys.SOCAT_code = cellstr(char(dataArray{1,1}(:)));
DriftingBuoys.Name = cellstr(char(dataArray{1,2}(:)));
DriftingBuoys.WMO =cellstr(char(dataArray{1,3}(:)));
DriftingBuoys.EDMO = cellstr(char(dataArray{1,4}(:)));
DriftingBuoys.Institute =cellstr(char(dataArray{1,5}(:)));

clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawNumericColumns rawStringColumns;

%% GLODAP cruises
filename = [workrootdir,...
    '04_2018/ReferenceData/Codes_for_Copernicus - GLODAP_cruises.tsv'];
delimiter = '\t';
startRow = 2;
formatSpec = '%s%s%s%s%s%s%s%s%[^\n\r]';
fileID = fopen(filename,'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);

GLODAPcruises.Cruise = cellstr(char(dataArray{1,1}(:)));
GLODAPcruises.Expocode = cellstr(char(dataArray{1,2}(:)));
GLODAPcruises.ICEScode = cellstr(char(dataArray{1,3}(:)));
GLODAPcruises.Name =cellstr(char(dataArray{1,4}(:)));
GLODAPcruises.Callsign=cellstr(char(dataArray{1,5}(:)));
GLODAPcruises.IMO=cellstr(char(dataArray{1,6}(:)));
GLODAPcruises.EDMO=cellstr(char(dataArray{1,7}(:)));
GLODAPcruises.Institute=cellstr(char(dataArray{1,8}(:)));

% Temp fix because it's one short
while length(GLODAPcruises.IMO)<length(GLODAPcruises.Cruise);
GLODAPcruises.IMO(length(GLODAPcruises.IMO)+1)={''};
end


clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawNumericColumns rawStringColumns;

%% Save file
save([workrootdir,...
    '04_2018/ReferenceData/PlatformCodes.mat'],...
    'ResearchVessels','ShipsofOpportunity','FixedMoorings','DriftingBuoys',...
'GLODAPcruises');

